"""add soft delete to users

Revision ID: 58d8ca04fa60
Revises: 
Create Date: 2025-12-10 15:29:55.085373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d8ca04fa60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add soft delete columns
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # Drop existing unique index on email
    op.drop_index('ix_users_email', table_name='users')

    # Create partial unique index - only enforce uniqueness for non-deleted users
    op.execute('CREATE UNIQUE INDEX idx_users_email_active ON users(email) WHERE is_deleted = FALSE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop partial unique index
    op.execute('DROP INDEX IF EXISTS idx_users_email_active')

    # Recreate original unique index
    op.create_index('ix_users_email', 'users', ['email'], unique=True)

    # Drop soft delete columns
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
