"""add oauth support to users

Revision ID: 8ba682d24ea3
Revises: 58d8ca04fa60
Create Date: 2025-12-11 03:19:57.449496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba682d24ea3'
down_revision = '58d8ca04fa60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create OAuthProvider enum type
    oauthprovider_enum = sa.Enum('LOCAL', 'GOOGLE', 'GITHUB', 'MICROSOFT', name='oauthprovider')
    oauthprovider_enum.create(op.get_bind(), checkfirst=True)

    # Add OAuth columns with default for existing rows
    op.add_column('users', sa.Column('oauth_provider', sa.Enum('LOCAL', 'GOOGLE', 'GITHUB', 'MICROSOFT', name='oauthprovider'), server_default='LOCAL', nullable=False))
    op.add_column('users', sa.Column('oauth_provider_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))

    # Make hashed_password nullable (OAuth users may not have passwords)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # Create index for oauth_provider_id lookups
    op.create_index(op.f('ix_users_oauth_provider_id'), 'users', ['oauth_provider_id'], unique=False)

    # Create partial unique constraint for OAuth provider combinations
    # This ensures one account per OAuth provider (e.g., can't have two Google accounts with same provider ID)
    op.execute(
        'CREATE UNIQUE INDEX idx_users_oauth_provider_unique '
        'ON users(oauth_provider, oauth_provider_id) '
        'WHERE oauth_provider_id IS NOT NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop partial unique index
    op.execute('DROP INDEX IF EXISTS idx_users_oauth_provider_unique')

    # Drop OAuth indexes and columns
    op.drop_index(op.f('ix_users_oauth_provider_id'), table_name='users')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')

    # Restore hashed_password to non-nullable
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # Drop the enum type
    sa.Enum(name='oauthprovider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
